### ISSUE TITLE
How to custom pragma to add the Permissions above of the class?

### ISSUE THREAD

**Issue by MonKeyXie** [guoxiao/odb#1]
你好，我想修改odb 编译器的源代码，增加一些pragma属性，如为类设置权限(一级管理员、二级管理员)，还想定义字段时增加附加属性、实现分表访问，如类名+单位ID （登录人员所在单位），希望能通过扩展#pragma来实现，请问我该怎么做？

**Comment by guoxiao** [comment]
我只是把这个项目镜像到了这，并不是很熟悉如何使用，所以你的问题我也不知道答案……

**Comment by MonKeyXie** [comment]
好的，谢谢啦~
